version: '3'

services: 
  app:
    # build: .
    image: quay.io/keycloak/keycloak:11.0.2
    container_name: keycloak_server
    environment: 
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_ADDR=db
      - DB_VENDOR=mysql
      - DB_DATABASE=keycloak
      - DB_PORT=3306
      - DB_PASSWORD=root
      - DB_USER=root
    volumes: 
      - ./meutema:/opt/jboss/keycloak/themes/meutema
    ports:
      - 8080:8080
    depends_on: 
      - db

  db:
    image: mysql:5.7
    container_name: keycloak_mysql
    restart: always
    tty: true
    ports: 
      - 33306:3306
    volumes: 
      - ./.docker/dbdata:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=keycloak
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root